### ISSUE TITLE
hitting deny in authorization screen does not do anything

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#107]
but confuse the agent ... no response, and accepting later has agent in a weird situation

**Comment by GregTurner** [comment]
fixed.  I globally stopped using the 'tap' event, instead I'm using 'click' which turns out is more predicable.

**Comment by watkinspd** [comment]
Deny still does not work for me. v1.5 - pressing deny does nothing.

**Comment by GregTurner** [comment]
Which app and by which method (QR, direct)?

**Comment by GregTurner** [comment]
fixed, this happened in QR code scenarios only
