### ISSUE TITLE
Resource request persisting across requests

### ISSUE THREAD

**Issue by dickhardt** [dickhardt/A2P3_agent#39]
I openned an account using agent on a2p3.net

I reset agent and set values to dev.a2p3.net

When logging into account, I am asked to release data for:

si.a2p3.net
si.dev.a2p3.net
people.a2p3.net
people.dev.a2p3.net

Looks like there is state being maintained between requests that should not be maintained.

**Comment by dickhardt** [comment]
![IMG_0964](https://f.cloud.github.com/assets/688982/116073/227e857e-6be8-11e2-8c22-51426dd7b4be.PNG)

**Comment by GregTurner** [comment]
fixed.  

For the curious... If you instantiate an object in a Backbone model defaults section, that instance is reused for all instances of the model.   Could be handy but not intuitive.

**Comment by dickhardt** [comment]
Still broken, and is worse.

Login to Clinic, open account in Bank, login to Bank.

![IMG_0968](https://f.cloud.github.com/assets/688982/116990/bb89ad08-6c14-11e2-9cd3-d56927621861.PNG)

**Comment by GregTurner** [comment]
For some reason this only happens on the phone.  I have to test in the
morning.

**Comment by GregTurner** [comment]
Unable to reproduce.  I'm going to send you a new agent for you to retest before I bang my head against the wall.
